version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: testing
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - requirements-{{ checksum "requirements.txt" }}
          - grablib-files-{{ checksum "grablib.yml" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install-all
            ./manage.py collectstatic --noinput --verbosity 0

      - save_cache:
          paths:
            - ./venv
          key: requirements-{{ checksum "requirements.txt" }}

      - save_cache:
          key: grablib-files-{{ checksum "grablib.yml" }}
          paths:
          - /stock-watch/StockWatch/static/libs/

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest StockWatch/ --tb=native --cov=StockWatch
            flake8 StockWatch/
            codecov --token=b62f2c75-fc41-4503-98ee-6a66d731f1e0 -e=.coveragec
      - store_artifacts:
          path: test-reports
          destination: test-reports
